# Generated by Django 5.1.4 on 2026-06-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_inboundendpoint_inboundevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundendpoint',
            name='action',
            field=models.CharField(choices=[('create_lead', 'Create lead'), ('log_email', 'Log email reply as a note')], default='create_lead', max_length=20),
        ),
    ]
