# Generated by Django 5.1.4 on 2026-06-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_stale',
            field=models.BooleanField(default=False),
        ),
    ]
